---
title: 'Testing the package on each spatiotemporal metric / example of how to use the package'
author: "S. J. Terian"
date: "8/24/2026"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries and Data
```{r}
#install.packages("devtools")
library(devtools)

install_github("sjterian/Watershed-metrics") #creator/repo name

library(watershedmetrics)
ls("package:watershedmetrics") #list functions to make sure that it worked

```

load the Gu data to use as an example for the package
```{r}
dat <- read.csv("data/Gu_StreamWaterChemistry_processed.csv")
date_col = "n.sampling"
site_col = "p.sampling"


```


## 1) Variance collapse ##
```{r}





```


## 2) Spatial CV ##
```{r}

spatial_cv(c(1, 2, 3, 4))

#test on the Gu data:

spatial_CVs <- execute_spatial_CV(dat, "nitrate", date_col)
print(spatial_CVs)

average_spatial_CV <- mean(spatial_CVs)
print(paste('Average Spatial CV:', average_spatial_CV)) #note: Gu's average for nitrate was 0.64


```



## 3) Temporal CV ##
```{r}

temporal_CVs <- execute_temporal_CV(dat, "nitrate", site_col)
print(temporal_CVs)

average_temporal_CV <- mean(temporal_CVs)
print(paste('Average Temporal CV:', average_temporal_CV)) #note: Gu's average for nitrate was 0.41

```


## 4) Spatial persistence ##
```{r}


nitrate_sp <- calculate_spatial_persistence(
  data = dat,
  concentration_col = "nitrate",
  site_col = "p.sampling",
  event_col = "n.sampling"
)


spatial_persistence_by_event <- nitrate_sp$by_event
print(spatial_persistence_by_event)

average_spatial_persistence <- mean(
  spatial_persistence_by_event$spatial_persistence,
  na.rm = TRUE
)

print(paste(
    "Average nitrate spatial persistence:",
    round(average_spatial_persistence, 3)
  ))


```


## 5) Temporal Synchrony ##
```{r}

sync_values <- tsync(dat, "nitrate", site_col, date_col)

print('Temporal Synchrony Values:')
print(sync_values)

average_sync <- mean(sync_values, na.rm = TRUE)
print(paste('Average Temporal Synchrony:', average_sync)) #note: Gu's average for nitrate was 0.60


```



## 6) Subcatchment leverage ##


**This is the one we can't compare with the Gu data on

```{r}

leverage <- calculate_subcatchment_leverage(
    data = dat,
    concentration_col = "nitrate",
    site_col = site_col,
    event_col = date_col,
    subcatchment_area_col = dat$surface.ha,
    contributing_area_col = dat$surface.ha, #conceptually wrong but just testing the function
    outlet_site = "P01",
    area_type = c("subcatchment", "contributing"),
    lower_threshold = -5,
    upper_threshold = 5
)


leverage

```


```{r}


```
